name: themefinder tests (UV)

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-uv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UV
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Run tests with Pytest
        run: uv run coverage run -m pytest -v -s

      - name: Generate coverage report
        run: |
          uv run coverage report -m --fail-under=85
          uv run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: matrix.python-version == '3.11'
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

  test-poetry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Run tests with Pytest
        run: |
          poetry run coverage run -m pytest -v -s

      - name: Generate coverage report
        run: |
          poetry run coverage report -m --fail-under=85
